version: '3'
networks:
   clasr-net:
        driver: overlay

#volumes:
#    recordings_saver:

services:
    mysql:
        image: mysql:5.7.19
        ports:
            - 3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=cloudasr
            - MYSQL_PASSWORD=cloudasr
            - MYSQL_DATABASE=cloudasr
        volumes:
            - ./deployment/script:/docker-entrypoint-initdb.d
            - ./resources/mysql_utf8.cnf:/etc/mysql/conf.d/mysql_utf8.cnf
        command: [--ssl=0]
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-uroot", "-proot"]
            interval: 10s
            timeout: 60s
            retries: 5
        networks:
            - clasr-net
    master:
        image: smartcommunitylab/cloud-asr-master:latest
        ports:
            - 5678:5678 #master_to_worker_port
            - 5679:5679 #master_to_api_port
        environment:
            - WORKER_ADDR=tcp://0.0.0.0:5678
            - API_ADDR=tcp://0.0.0.0:5679
            - MONITOR_ADDR=tcp://monitor:5680
        networks:
            - clasr-net
    monitor:
        image: smartcommunitylab/cloud-asr-monitor:latest
        ports:
            - 8001:80 #monitor_host_port
            - 5680:5680 #monitor_status_port
        environment:
            - MONITOR_ADDR=tcp://0.0.0.0:5680
        networks:
            - clasr-net
    recordings:
        image: smartcommunitylab/cloud-asr-recordings:latest
        ports:
            - 8002:80 #recordings_host_port    
            - 5682:5682 #recordings_saver_port
        volumes:
            - ./recordings:/opt/app/static/data
        depends_on:
            - mysql        
        environment:
            - CONNECTION_STRING=mysql://cloudasr:cloudasr@mysql:3306/cloudasr?charset=utf8
            - STORAGE_PATH=/opt/app/static/data
            - DOMAIN=http://localhost:80
        networks:
            - clasr-net
    api:
        image: smartcommunitylab/cloud-asr-api:latest
        ports:
            - 8000:80 #api_host_port
        depends_on:
             - mysql
        environment:
            - CONNECTION_STRING=mysql://cloudasr:cloudasr@mysql:3306/cloudasr?charset=utf8
            - MASTER_ADDR=tcp://master:5679
        networks:
            - clasr-net
    web:
        image: smartcommunitylab/cloud-asr-web:latest
        ports:
            - 8003:80 #web_host_port
        depends_on:
            - mysql
        environment:
            - CONNECTION_STRING=mysql://cloudasr:cloudasr@mysql:3306/cloudasr?charset=utf8
            - API_URL=http://api:8000
            - MASTER_ADDR=tcp://master:5678
            - RECORDINGS_SAVER_ADDR=tcp://recordings:5682
            - GOOGLE_LOGIN_CLIENT_ID=""
            - GOOGLE_LOGIN_CLIENT_SECRET=""
            - GA_TRACKING_ID=""
        networks:
            - clasr-net
    worker:
        image: smartcommunitylab/cloud-asr-worker-it-small:latest 
        ports:
            - 5678
        volumes:
#            - ./cloudasr/worker:/opt/app
            - ./init.sh:/opt/app/init.sh
        environment:
            - MASTER_ADDR=tcp://master:5678
            - RECORDINGS_SAVER_ADDR=tcp://recordings:5682
            - MODEL=it-small
#            - HOST=192.168.56.105
            - PORT0=5678
        entrypoint: /opt/app/init.sh
        deploy:
            mode: replicated
            replicas: 1 
        networks:
            - clasr-net
