apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: cloud-asr
spec:
  ports:
    - port: 3306
  selector:
    app: cloud-asr
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: cloud-asr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: cloud-asr
spec:
  selector:
    matchLabels:
      app: cloud-asr
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cloud-asr
        tier: mysql
    spec:
      containers:
      - image: mysql:5.7.19
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: root_password
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: MYSQL_USER
          value: "cloudasr"
        - name: MYSQL_DATABASE
          value: "cloudasr"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim



                


