apiVersion: v1
kind: Service
metadata:
  name: recordings-host-port
  labels:
    app: cloud-asr
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
      name: recordings-host
  selector:
    app: cloud-asr
    tier: recordings
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: recordings
  labels:
    app: cloud-asr
spec:
  ports:
    - port: 5682 
      targetPort: 5682
      name: recordings-saver
  selector:
    app: cloud-asr
    tier: recordings
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recordings-pv-data
  labels:
    app: cloud-asr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recordings
  labels:
    app: cloud-asr
spec:
  selector:
    matchLabels:
      app: cloud-asr
      tier: recordings
  template:
    metadata:
      labels:
        app: cloud-asr
        tier: recordings
    spec:
      containers:
        - image: smartcommunitylab/cloud-asr-recordings
          name: recordings
          ports:
            - containerPort: 80
              name: recording-host
            - containerPort: 5682
              name: recording-save
          env:
            - name: CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: connection-string
                  key: string
            - name: STORAGE_PATH
              value: "/opt/app/static/data"
            - name: DOMAIN
              value: "http://recordings:30002"
          volumeMounts:
            - name: recordings-data
              mountPath: /opt/app/static/data
      volumes:
        - name: recordings-data
          persistentVolumeClaim:
                claimName: recordings-pv-data


