apiVersion: apps/v1
kind: Deployment
metadata:
  name: recordings
  labels:
    app: cloud-asr
spec:
  selector:
    matchLabels:
      app: cloud-asr
      tier: recordings
  template:
    metadata:
      labels:
        app: cloud-asr
        tier: recordings
    spec:
      nodeSelector:
        kubernetes.io/hostname: k82
      containers:
        - image: smartcommunitylab/cloud-asr-recordings
          name: recordings
          ports:
            - containerPort: 80
              name: recording-host
            - containerPort: 5682
              name: recording-save
          env:
            - name: CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: connection-string
                  key: string
            - name: STORAGE_PATH
              value: "/opt/app/static/data"
            - name: DOMAIN
              value: "http://recordings:30002"

