apiVersion: v1
kind: Service
metadata:
  name: monitor 
  labels:
    app: cloud-asr
spec:
  ports:
    - port: 8001
      targetPort: 80
      name: monitor_host_port
      port: 5680 
      targetPort: 5680
      name: monitor_status_port
  selector:
    app: cloudasr
    tier: monitor
---
apiVersion: v1
kind: Deployment
metadata:
  name: monitor
  labels:
    app: cloud-asr
spec:
  selector:
    matchLabels:
      app: cloud-asr
      tier: monitor
  template:
    metadata:
      labels:
        app: cloud-asr
        tier: monitor
    spec:
      containers:
        - image: smartcommunitylab/cloud-asr-monitor
          name: monitor
          ports:
            - containerPort: 80
              name: monitor_host_port
            - containerPort: 5680
              name: monitor_status_port
          env:
            - name: MONITOR_ADDR
              value: tcp://0.0.0.0:5680


