apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor
  labels:
    app: cloud-asr
spec:
  selector:
    matchLabels:
      app: cloud-asr
      tier: monitor
  template:
    metadata:
      labels:
        app: cloud-asr
        tier: monitor
    spec:
      nodeSelector:
        kubernetes.io/hostname: k82
      containers:
        - image: smartcommunitylab/cloud-asr-monitor
          name: monitor
          ports:
            - containerPort: 80
              name: monitor-host
            - containerPort: 5680
              name: monitor-status
          env:
            - name: MONITOR_ADDR
              value: "tcp://0.0.0.0:5680"


