apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: cloud-asr
spec:
  selector:
    matchLabels:
      app: cloud-asr
      tier: worker
  template:
    metadata:
      labels:
        app: cloud-asr
        tier: worker
    spec:
      nodeSelector:
        kubernetes.io/hostname: k83
      containers:
        - image: smartcommunitylab/cloud-asr-worker-it-small
          name: worker
          ports:
            - containerPort: 5678
              name: worker-host
          env:
            - name: CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: connection-string
                  key: string
            - name: MASTER_ADDR
              value: "tcp://master:5678"
            - name: API_URL
              value: "http://api:30000"
            - name: RECORDINGS_SAVER_ADDR
              value: "tcp://recordings:5682"
            - name: MODEL
              value: "it-small"
            - name: PORT0
              value: "5678"
