version: "3"
services:
  master:
    image: jenkins/jenkins:lts-alpine
    deploy:
            placement:
                constraints: [node.labels.task == manager]
    ports:
     - '8080:8080'
     - '50000:50000'
    volumes:
     - 'master_data:/var/jenkins_home'
volumes:
  master_data:
