version: '3.7'
networks:
  asr-manager_clasr-net:
    external: true

services:
  worker:
    image: smartcommunitylab/cloud-asr-worker-en-towninfo:latest
    ports:
      - 5678
    environment:
      - MASTER_ADDR=tcp://master:5678
      - RECORDINGS_SAVER_ADDR=tcp://recordings:5682
      - MODEL=en-towninfo
      - PORT0=5678
    entrypoint: 
      - /opt/app/init.sh
    deploy:
      placement:
        constraints: [node.labels.model == en-towninfo]
      mode: replicated
      replicas: 1
    networks:
      - asr-manager_clasr-net

